spring:
  profiles:
    active: local

  messages:
    basename: classpath:/messages/message
    encoding: UTF-8

#mybatis:
#  executor-type: REUSE
#  mapper-locations:
#    - "classpath:/mappers/default-maps/*.xml"

